[[sources]]
  name = "gencode"
  version = "48"
  format = "gtf"
  url = "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_48/gencode.v48.annotation.gtf.gz"

  [[sources.annotations]]
    name = "GENCODE_48_GENE"
    field = "GENE"

  [[sources.annotations]]
    name = "GENCODE_48_GENEID"
    field = "GENEID"

  [[sources.annotations]]
    name = "GENCODE_48_STRAND"
    field = "STRAND"

  [[sources.annotations]]
    name = "GENCODE_48_BIOTYPE"
    field = "BIOTYPE"

  [[sources.annotations]]
    name = "GENCODE_48_REGION"
    field = "REGION"

  [[sources.annotations]]
    name = "GENCODE_48_CODING_GENE"
    field = "CODING"

  [[sources.annotations]]
    name = "GENCODE_48_NONCODING_GENE"
    field = "NONCODING"
